matrix:
  include:
  - env: BUILD_TYPE=ONCE
    node_js: 8.3.0
  - env: BUILD_TYPE=ONCE
    node_js: 8.5.0
  - env: BUILD_TYPE=ONCE
    node_js: 8.9.0
  - env: BUILD_TYPE=ONCE
    node_js: 8.11.1
  - env: BUILD_TYPE=ONCE
    node_js: 9.0.0
  - env: BUILD_TYPE=ONCE
    node_js: 9.5.0

before_install:
  - npm -g install npm@5.6.0
  - npm -g install yarn

install:
  - npm link
  - npm install

script:
  - if [[ $BUILD_TYPE == 'ONCE' ]]; then npm run test:local; fi

branches:
  only:
    - master
